### ISSUE TITLE
Implement the nonogram game 🎯

### ISSUE THREAD

**Issue by boroboro01** [boroboro01/Nonogram#1]
# Description
Implement the nonogram game for Mobile Programming Project

# Tasks
- [ ] Design the UI
- [ ] Create a black square
- [ ] Create the `Cell` class
- [ ] Implement game control logic
- [ ] Test the game

# Example
![image](https://github.com/user-attachments/assets/8ff685a0-3d8c-4813-8636-726aa460edcf)
